version: '3.4'

volumes:
  database-data:
    driver: local
  php-socket:
    driver: local

services:
  database-server:
    image: postgres:14
    container_name: phpmysupport-database-server
    environment:
      POSTGRES_DB: "phpmysupport"
      POSTGRES_USER: "phpmysupport"
      POSTGRES_PASSWORD: "phpmysupport"
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./:/data/

  php-fpm:
    image: ghcr.io/waltertamboer/phpmysupport:php81-fpm-dev
    build:
      context: ./
      dockerfile: .docker/php-fpm/Dockerfile
      target: development
    container_name: phpmysupport-php-fpm
    volumes:
      - ./:/opt/phpmysupport
      - php-socket:/var/run/php
    user: "0"
    working_dir: /opt/phpmysupport
    links:
      - database-server

  webserver:
    image: ghcr.io/waltertamboer/phpmysupport:nginx
    build:
      context: ./
      dockerfile: .docker/nginx/Dockerfile
    container_name: phpmysupport-webserver
    volumes:
      - ./:/opt/phpmysupport
      - php-socket:/var/run/php
    working_dir: /opt/phpmysupport
    links:
      - database-server
    environment:
      - VIRTUAL_HOST=phpmysupport.docker
      - VIRTUAL_PORT=8080
