name: Docker

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [ "Test" ]
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to registry
        run: echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
        env:
          GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
          GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}

      - name: Build docker image
        run: echo Build ghcr.io/OWNER/IMAGE_NAME:latest

      - name: Publish docker image
        run: echo Push
