name: Docker

on:
  push:
    branches: [ master ]
  workflow_run:
    workflows: [ "Test" ]
    types:
      - completed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Composer dependencies
        run: composer install --no-dev -o

      - name: Login to registry
        run: echo $GHCR_TOKEN | docker login ghcr.io -u $GHCR_USERNAME --password-stdin
        env:
          GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
          GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}

      - name: Build NGINX
        run: docker build -t ghcr.io/waltertamboer/php-support-system:nginx --file .docker/nginx/Dockerfile .

      - name: Build PHP-FPM Production
        run: docker build --force-rm --target production --tag ghcr.io/waltertamboer/php-support-system:php81-fpm --file .docker/php-fpm/Dockerfile .

      - name: Build PHP-FPM Dev
        run: docker build --force-rm --target development --tag ghcr.io/waltertamboer/php-support-system:php81-fpm-dev --file .docker/php-fpm/Dockerfile .

      - name: Build PHP-FPM CI
        run: docker build --force-rm --target ci --tag ghcr.io/waltertamboer/php-support-system:php81-fpm-ci --file .docker/php-fpm/Dockerfile .

      - name: Publishing ghcr.io/waltertamboer/php-support-system:nginx
        run: docker push ghcr.io/waltertamboer/php-support-system:nginx

      - name: Publishing ghcr.io/waltertamboer/php-support-system:php81-fpm
        run: docker push ghcr.io/waltertamboer/php-support-system:php81-fpm

      - name: Publishing ghcr.io/waltertamboer/php-support-system:php81-fpm-dev
        run: docker push ghcr.io/waltertamboer/php-support-system:php81-fpm-dev

      - name: Publishing ghcr.io/waltertamboer/php-support-system:php81-fpm-ci
        run: docker push ghcr.io/waltertamboer/php-support-system:php81-fpm-ci
